image: python:3.14-trixie

before_script:
  - pip install zensical

pages:
  stage: deploy
  script:
  - cd docs
  - zensical build
  - mv public ../public
  - cd ..
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
