[question_labels]
question = "Савол"
answer = "Жавоб"
zachet = "Қабул"
nezachet = "-"
comment = "Изоҳ"
source = "Манба"
sources = "Манба"
author = "Муаллиф"
authors = "Муаллифлар"
handout = "Тарқатма материал"
handout_short = "Тарқат"

[general]
section = "Тур"
editor = "Муҳаррир"
date = "Сана"
questions_in_comments = "-"
handout_for_question = "-"
general_impressions_caption = "-"
general_impressions_text = "-"
right_answers_for_stats = "-"